-- Migration: Advisor Invite System (S1-C)
-- Purpose: Allow existing advisors to invite new advisors via codes

-- Create advisor invites table
CREATE TABLE IF NOT EXISTS public.advisor_invites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invited_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  invite_code text NOT NULL UNIQUE,
  email text,
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  accepted_at timestamptz,
  accepted_by uuid REFERENCES public.profiles(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Index for fast code lookup
CREATE INDEX IF NOT EXISTS idx_advisor_invites_code ON public.advisor_invites(invite_code);

-- Enable RLS
ALTER TABLE public.advisor_invites ENABLE ROW LEVEL SECURITY;

-- Only advisors/admins can create invites
CREATE POLICY "advisor_invites_insert" ON public.advisor_invites
  FOR INSERT WITH CHECK (
    auth.uid() IN (
      SELECT id FROM public.profiles
      WHERE role IN ('advisor', 'admin')
    )
  );

-- Advisors can view invites they created
CREATE POLICY "advisor_invites_select_own" ON public.advisor_invites
  FOR SELECT USING (invited_by = auth.uid());

-- Anyone authenticated can read by code (to validate during acceptance)
CREATE POLICY "advisor_invites_select_by_code" ON public.advisor_invites
  FOR SELECT USING (auth.uid() IS NOT NULL);

-- Function to accept advisor invite
CREATE OR REPLACE FUNCTION public.accept_advisor_invite(invite_code_input text)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  invite_record record;
BEGIN
  SELECT * INTO invite_record
  FROM public.advisor_invites
  WHERE upper(invite_code) = upper(invite_code_input)
  FOR UPDATE;

  IF invite_record IS NULL THEN
    RAISE EXCEPTION 'Invite not found';
  END IF;

  IF invite_record.accepted_at IS NOT NULL THEN
    RAISE EXCEPTION 'Invite already used';
  END IF;

  IF invite_record.expires_at < now() THEN
    RAISE EXCEPTION 'Invite expired';
  END IF;

  -- Update invite as accepted
  UPDATE public.advisor_invites
  SET accepted_at = now(), accepted_by = auth.uid()
  WHERE id = invite_record.id;

  -- Update user's role to advisor
  UPDATE public.profiles
  SET role = 'advisor'
  WHERE id = auth.uid();

  -- Create advisor_profile if not exists
  INSERT INTO public.advisor_profiles (user_id)
  VALUES (auth.uid())
  ON CONFLICT (user_id) DO NOTHING;

  RETURN invite_record.id;
END;
$$;

-- Grant execute to authenticated users
GRANT EXECUTE ON FUNCTION public.accept_advisor_invite(text) TO authenticated;

-- Comments for documentation
COMMENT ON TABLE public.advisor_invites IS 'Invite codes for new advisors, generated by existing advisors';
COMMENT ON FUNCTION public.accept_advisor_invite(text) IS 'Accept an advisor invite code, updating user role to advisor';
